name: Rust

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt update && sudo apt install -y libsdl2-dev 
    - name: Load cache
      uses: actions/cache@v3
      with:
        path: target
        key: target
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Do a render
      run: cargo run -- data/scenes/scene1.yml --output image.png